"""add origin and payload to shipment

Revision ID: 7866e10381e7
Revises: b042a021864a
Create Date: 2026-03-31 13:03:23.403383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7866e10381e7'
down_revision: Union[str, None] = 'b042a021864a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'route_stops', 'delivery_points', ['delivery_point_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'depots', ['depot_id'], ['id'])
    op.add_column('shipments', sa.Column('origin_name', sa.String(length=255), nullable=True))
    op.add_column('shipments', sa.Column('origin_address', sa.Text(), nullable=True))
    op.add_column('shipments', sa.Column('origin_lat', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('origin_lng', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('total_items', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('total_weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'total_weight_kg')
    op.drop_column('shipments', 'total_items')
    op.drop_column('shipments', 'origin_lng')
    op.drop_column('shipments', 'origin_lat')
    op.drop_column('shipments', 'origin_address')
    op.drop_column('shipments', 'origin_name')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'route_stops', type_='foreignkey')
    # ### end Alembic commands ###
