"""add_status_to_delivery_point_and_route_stop

Revision ID: b042a021864a
Revises: b74a1234cdef
Create Date: 2026-03-26 07:57:31.802674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b042a021864a'
down_revision: Union[str, None] = 'b74a1234cdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_points', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('route_stops', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'diesel'::character varying"))
    op.alter_column('vehicles', 'fuel_capacity_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('60.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'fuel_capacity_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('60.0'))
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'diesel'::character varying"))
    op.drop_column('route_stops', 'status')
    op.drop_column('delivery_points', 'status')
    # ### end Alembic commands ###
