"""add_spark_id_to_vehicle_v2

Revision ID: d619b51920ae
Revises: 7866e10381e7
Create Date: 2026-03-31 14:48:11.151305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd619b51920ae'
down_revision: Union[str, None] = '7866e10381e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('spark_id', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_vehicles_spark_id'), 'vehicles', ['spark_id'], unique=False)
    op.drop_column('vehicles', 'cargo_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('cargo_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicles_spark_id'), table_name='vehicles')
    op.drop_column('vehicles', 'last_sync')
    op.drop_column('vehicles', 'spark_id')
    # ### end Alembic commands ###
